on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - 'RobustToolbox/'
      - '.github/workflows/update-wiki-json.yml'
      - 'Content.Server/GuideGenerator/**.cs'
      - 'Content.Shared/Chemistry/**.cs'
      - 'Content.Server/Chemistry/**.cs'
      - 'Content.Server/_White/GuideGenerator/**.cs'
      - 'Content.Server/Research/Systems/**.cs'
      - 'Content.Shared/Research/Prototypes'
      - 'Resources/Prototypes/Research/**.yml'
      
permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  update-wiki:
    name: Build and Publish JSON blobs to wiki
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        repository: ProstoGavrik/wiki_json_prototypes
        path: target-repo
        ssh-key: ${{ secrets.TARGET_REPO_TOKEN }}

    - name: Copy files
      uses: canastro/copy-file-action@master
      with:
        source: ".github/workflows/update-wiki-json.yml"
        target: "target-repo/"

    - name: Commit changes
      working-directory: target-repo
      run: |
        git add .
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -m "Update json files via GitHub Action"
        git request-pull https://github.com/ProstoGavrik/wiki_json_prototypes master
