on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - 'RobustToolbox/'
      - '.github/workflows/update-wiki-json.yml'
      - 'Content.Server/GuideGenerator/**.cs'
      - 'Content.Shared/Chemistry/**.cs'
      - 'Content.Server/Chemistry/**.cs'
      - 'Content.Server/_White/GuideGenerator/**.cs'
      - 'Content.Server/Research/Systems/**.cs'
      - 'Content.Shared/Research/Prototypes'
      - 'Resources/Prototypes/Research/**.yml'

jobs:
  update-wiki:
    name: Build and Publish JSON blobs to wiki
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3.6.0

    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        repository: https://github.com/ProstoGavrik/wiki_json_prototypes
        path: target-repo
        token: ${{ secrets.TARGET_REPO_TOKEN }}
